### ISSUE TITLE
Implement Burn Tax in All Necessary TXs

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-extension#10]
WHAT: Implement burn tax payed for  specific TXs
WHY: Show end users that the tax was actually implemented
WHO: Classic Network end users

**Tasks:**
- [x] Add 1.2% burn tax information to all components or views that require it.
- [x] Check what other views would need to display the burn tax info.
- [x] Ensure the tax gets charged for the following TX types: MsgSend, MsgExec,
MsgMultiSend, MsgSwapSend, MsgInstantiateContract, MsgExecuteContract.
- [x] Test code changes on rebel-1 and classic networks.

**Acceptance criteria:**
- [x] All necessary views of the platform should show the correct burn tax amount.
- [x] All tests on rebel-1 and classic for each one of the targeted TX types should pass.
