### ISSUE TITLE
Codebase Revision and Analysis (Critical and High)

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-extension#6]
**Task Fundamentals:**
WHAT: We need to perform a full regression analysis and secops audit on the mobile-station repository
WHY: Because we have identified several HIGH severity vulnerabilities.

Tasks:
- [ ] SecOps analysis of mobile-station using SNYK tooling
- [ ] Fix identified Critical and High CVE/CWE's
- [ ] Re-run SNYK tooling to verify fixable Critical and High vulnerabilities have been patched

Acceptance criteria:
- [ ] SecOps analysis published as postmortem
- [ ] Critical and High CVE/CWEs are fixed in local repository
- [ ] SNYK tooling no longer identifies fixable Critical and High CVE/CWEs
