### ISSUE TITLE
Visual UX and Rebranding Changes

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-extension#7]
**Task Fundamentals:**
WHAT: We need to update UX and branding visuals
WHY: To distinguish ourselves from Terra V2
HOW: Scope of this task may vary depending on the scale of the rebranding we wish to make.

**Tasks:**
- [ ] Implement new UI delivered by the Creativity or Operations Team.
- [ ] Create two main themes implementing this new UI: light and dark.
- [ ] Test new version of the repo on local server.
- [ ] Test new version of the repo on rebel-1 testnet.

**Acceptance criteria:**
- [ ] New UI implemented on the mobile app.
- [ ] Ability to switch between light and dark theme successfully.
- [ ] Test on local server successfully.
- [ ] Tested on rebel-1 testnet successfully.
