### ISSUE TITLE
Make Repo Independent from Terra

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-extension#8]
**Task Fundamentals:**
WHAT: Make the repository 100% independent from any terra-money code
WHY: Avoiding dependencies will shield us from breaking changes introduced in v2.

**Tasks:**
- [ ] Rename the repo and rescope it to our @terra-rebels NPM organization.
- [ ] Ensure commit history to ensure our repo from `terra-money` was done before the v2 fork. Document the associated for commit ID and details in the README.
- [ ] Replace any NPM package dependencies and references pointing to @terra-money with our own NPM packages.
- [ ] Make sure all necessary NPM public packages needed for this repo have been forked and published under our NPM org.
- [ ] Update existing README and documentation to remove references to Terra websites and platforms.

**Acceptance criteria:**
- [ ] PR with necessary changes is thorough and includes README.md additions or changes.
- [ ] No NPM dependencies are missing from the NPM @terra-rebels org.
