### ISSUE TITLE
Review and Improve Localizations

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-extension#9]
**Task Fundamentals:**
WHAT: Review and improve translations of platform texts into other languages.
WHY: Make the platform more accessible and grow its user base.

**Tasks:**
- [ ] Review and fix existing translations in languages known to us.
- [ ] Make sure all texts are properly wrapped around a localization method.

**Acceptance Criteria:**
- [ ] All weird or funny-reading translations are fixed and improved.
- [ ] Translations into other languages cover at least 90% of existing EN text.
